### ISSUE TITLE
CONSIGNA GRAL

### ISSUE THREAD

**Issue by FrancoSer** [FrancoSer/First#2]
Investigar cuáles son las ceremonias en Scrum que son y cuáles son ,  ceremonias artefactos y roles.

Fecha de entrega (aprox): 3/5/2022 o 6/5/2022

**Comment by FrancoSer** [comment]
Ceremonias que se realizan a lo largo del proyecto:
● Sprint Planning Meeting
● Daily Scrum Meeting
● Sprint Review Meeting
● Sprint Retrospective Meetin

●Sprint Planning Meeting (reunión de planificación del sprint). Se produce al iniciar cada Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.
● Daily Scrum Meeting (reunión periódica). Se produce diariamente, y tiene un máximo de 20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.
● Sprint Review Meeting (reunión de revisión del Sprint). Se produce al finalizar el Sprint y tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el Product Owner.
● Sprint Retrospective Meeting (reunión de retrospectiva del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.

Fuente: Material de la cátedra: SCRUM

**Comment by FrancoSer** [comment]
![image22](https://user-images.githubusercontent.com/106319133/170799507-1a735684-eafb-4030-98ca-b38e7a0600f2.png)
![image11](https://user-images.githubusercontent.com/106319133/170799509-b5fea11e-abb9-45ec-b000-ef8c295b81a0.png)

Estimados, 

De acuerdo a lo que vamos a ir comunicando en las clases sincrónicas, con respecto al proyecto colaborativo en GitHub, aplicando las metodologías ágiles con Scrum, (leer la Guia de estudio) se propone organizarse en Grupos de 10 personas, seleccionar a un Scrum Master y completar el siguiente form Registro de grupos - Proyecto

El material de lectura y actividad en Git y GitHub.

Formulario de grupo. Completar con Correo y usuario GitHub de cada participante.

https://docs.google.com/forms/d/e/1FAIpQLSdNrdptlp8prG8vKtW7XpXH0of2EdLphUvkEAiDR6IQQsVYag/viewform

**Comment by RodrigoG24** [comment]
<img width="785" alt="Sprint_Planning_Gráfica" src="https://user-images.githubusercontent.com/94760740/171965946-c9f9f1c3-49c0-4636-8506-da965f454c63.png">




> Ceremonias que se realizan a lo largo del proyecto: ● Sprint Planning Meeting ● Daily Scrum Meeting ● Sprint Review Meeting ● Sprint Retrospective Meetin
> 
> ●Sprint Planning Meeting (reunión de planificación del sprint). Se produce al iniciar cada Sprint y tiene por objetivo decidir que se va a realizar en el Sprint. ● Daily Scrum Meeting (reunión periódica). Se produce diariamente, y tiene un máximo de 20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria. ● Sprint Review Meeting (reunión de revisión del Sprint). Se produce al finalizar el Sprint y tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el Product Owner. ● Sprint Retrospective Meeting (reunión de retrospectiva del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.
> 
> Fuente: Material de la cátedra: SCRUM
![maxresdefault](https://user-images.githubusercontent.com/94760740/171966045-18832f72-2434-4031-955d-ee3ac287a62c.jpg)
