### ISSUE TITLE
Ampliar info: Sprint Retrospective Meeting (reunión de retrospectiva del Sprint)

### ISSUE THREAD

**Issue by FrancoSer** [FrancoSer/First#6]
_● Sprint Retrospective Meeting (reunión de retrospectiva del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal._

Ampliar definición, buscar ejemplos, sumar material (videos, graficos, etc.).

**Comment by janu-ss** [comment]
El Sprint Retrospective es el último evento del Sprint y es la oportunidad para que el Equipo Scrum se analice a sí mismo y haga una propuesta de mejoras para que el desarrollo del siguiente Sprint sea más eficiente. Se debe realizar después del Sprint Review y antes del siguiente Sprint Planning.

El Scrum Master asiste como miembro del equipo y debe asegurarse que el evento se lleva a cabo y que los asistentes, tanto el Development Team como el Product Owner, entienden su propósito.

- ¿Quiénes asisten al Sprint Retrospective?
Al Sprint Retrospective asisten todos los miembros del Equipo Scrum, incluido el Scrum Master que participa como un miembro activo más, su función es motivar al Equipo para que mejore, dentro del marco Scrum, su proceso de desarrollo y sus prácticas para que los Sprint sean más eficientes.

- ¿Cuánto dura el Sprint Retrospective?

La duración máxima del Sprint Retrospective debe ser de 3 horas, y al igual que el Sprint Review, su tiempo es proporcional a la duración del Sprint; así que para que el Sprint Retrospective sea de 3 horas, debe ser un Sprint de 4 semanas o un mes, y así ir bajando proporcionalmente según las semanas del Sprint.

FUENTE: https://donetonic.com/es/diferencias-entre-el-sprint-review-y-el-sprint-retrospective/#Sprint_Retrospective
